// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"database/sql"
)

type Author struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	NumberOfBooks int64          `json:"number_of_books"`
	Bio           sql.NullString `json:"bio"`
}

type Book struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Author      int64         `json:"author"`
	Description string        `json:"description"`
	Price       float64       `json:"price"`
	Quantity    int64         `json:"quantity"`
	CategoryID  sql.NullInt64 `json:"category_id"`
}

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Invoice struct {
	ID            int64          `json:"id"`
	OrderID       int64          `json:"order_id"`
	InvoiceDate   sql.NullTime   `json:"invoice_date"`
	TotalAmount   float64        `json:"total_amount"`
	Status        int64          `json:"status"`
	PaymentMethod sql.NullString `json:"payment_method"`
}

type Order struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Status     int64        `json:"status"`
	TotalPrice float64      `json:"total_price"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type OrderItem struct {
	ID       int64   `json:"id"`
	OrderID  int64   `json:"order_id"`
	BookID   int64   `json:"book_id"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type Payment struct {
	ID            int64        `json:"id"`
	InvoiceID     int64        `json:"invoice_id"`
	Amount        string       `json:"amount"`
	PaymentDate   sql.NullTime `json:"payment_date"`
	PaymentMethod string       `json:"payment_method"`
	Status        int64        `json:"status"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Password  string         `json:"password"`
	Email     string         `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
