// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthor(ctx context.Context, id int64) error
	DeleteBook(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteInvoice(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteOrderItem(ctx context.Context, id int64) error
	DeletePayment(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllAuthors(ctx context.Context) ([]Author, error)
	GetAllBooks(ctx context.Context) ([]Book, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAllInvoices(ctx context.Context) ([]Invoice, error)
	GetAllOrderItems(ctx context.Context) ([]OrderItem, error)
	GetAllOrders(ctx context.Context) ([]Order, error)
	GetAllPayments(ctx context.Context) ([]Payment, error)
	GetAlluser(ctx context.Context) ([]User, error)
	GetAuthorByID(ctx context.Context, id int64) (Author, error)
	GetBookByID(ctx context.Context, id int64) (Book, error)
	GetBooksByAuthor(ctx context.Context, author int64) ([]Book, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetInvoiceByOrderID(ctx context.Context, orderID int64) (Invoice, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error)
	GetOrdersByUserID(ctx context.Context, userID int64) ([]Order, error)
	GetPaymentsByInvoiceID(ctx context.Context, invoiceID int64) ([]Payment, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
