// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"context"
)

type Querier interface {
	CheckoutBook(ctx context.Context, id int64) error
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	GetBookByID(ctx context.Context, id int64) (Book, error)
	GetBooks(ctx context.Context) ([]Book, error)
	ReturnBook(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
